// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIBLwz50O3l8fzk5M4qbNm0tBxc5M21Vw',
    appId: '1:809026658227:web:fa87841cc368156f4d75c6',
    messagingSenderId: '809026658227',
    projectId: 'ajarin-10d91',
    authDomain: 'ajarin-10d91.firebaseapp.com',
    storageBucket: 'ajarin-10d91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFH9PHysTsFJGfItLn5jcDBZoULa17T0',
    appId: '1:809026658227:android:92d54a43de89443f4d75c6',
    messagingSenderId: '809026658227',
    projectId: 'ajarin-10d91',
    storageBucket: 'ajarin-10d91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-p50Jf_AxsQfU0yoSS2TAU16D1z8xng',
    appId: '1:809026658227:ios:2acd1de036754a644d75c6',
    messagingSenderId: '809026658227',
    projectId: 'ajarin-10d91',
    storageBucket: 'ajarin-10d91.appspot.com',
    iosBundleId: 'com.example.ticketsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf-p50Jf_AxsQfU0yoSS2TAU16D1z8xng',
    appId: '1:809026658227:ios:2acd1de036754a644d75c6',
    messagingSenderId: '809026658227',
    projectId: 'ajarin-10d91',
    storageBucket: 'ajarin-10d91.appspot.com',
    iosBundleId: 'com.example.ticketsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIBLwz50O3l8fzk5M4qbNm0tBxc5M21Vw',
    appId: '1:809026658227:web:e6f015eeec8b5ac04d75c6',
    messagingSenderId: '809026658227',
    projectId: 'ajarin-10d91',
    authDomain: 'ajarin-10d91.firebaseapp.com',
    storageBucket: 'ajarin-10d91.appspot.com',
  );
}
